// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/13/2026, 1:26:39 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/ramki/support-aaryaits/support-aaryaits-nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ramki/support-aaryaits/support-aaryaits-nuxt/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ramki/support-aaryaits/support-aaryaits-nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ramki/support-aaryaits/support-aaryaits-nuxt/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ramki/support-aaryaits/support-aaryaits-nuxt/plugins/**/*.{js,ts,mjs}","/Users/ramki/support-aaryaits/support-aaryaits-nuxt/composables/**/*.{js,ts,mjs}","/Users/ramki/support-aaryaits/support-aaryaits-nuxt/utils/**/*.{js,ts,mjs}","/Users/ramki/support-aaryaits/support-aaryaits-nuxt/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ramki/support-aaryaits/support-aaryaits-nuxt/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/ramki/support-aaryaits/support-aaryaits-nuxt/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/ramki/support-aaryaits/support-aaryaits-nuxt/app.config.{js,ts,mjs}","/Users/ramki/support-aaryaits/support-aaryaits-nuxt/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;